# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: SC-GroupHK # title of site, used in tab name and elsewhere
email: sheng.chen@polyu.edu.hk # default email
google: Sheng Chen # default name to search on Google Scholar
github: SC-GroupHK/SC-GroupHK.github.io # default GitHub user/org, without the @
# twitter: nomad421 # default Twitter handle, without the @
#instagram: fakeinstagramhandle # default Instagram handle, without the @
#youtube: fakeyoutubechannel # default YouTube channel handle

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: "/"

# default front matter parameters for markdown files
# defaults can be overridden on a particular page, eg:
# ---
# description: Description unique to this page
# background: images/different-bg-for-this-page.jpg
# ---
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more. # description that will show under search engine results
      background: images/back1.jpg # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /newsposts
  - scope:
      path: "newsposts"
    values:
      layout: post
  - scope:
      path: "assets/cv"
    values:
      layout: default
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
excerpt_separator: "<!--more-->"
